[자동차 경주] 이윤하 미션 제출합니다.
gdsc-skhu-pair-mission/kotlin-racingcar-6 pull request #1
Opened 2024-04-08 10:00 UTC by labyrinth30

## 미션2 자동차 경주
### 1. 미션을 진행하며
현수님과 code with me 환경에서 진행하였습니다. 저는 드라이버, 현수님이 네비게이터를 맡아 구현하였습니다.
프레임워크에서 제공해주는 방식으로 mvc 패턴에 따라 구현한 적은 있지만, 그런 것 없이 생으로 mvc 패턴을 구현하려니 낯설게 느껴졌습니다. 2시간 정도 페어 프로그래밍을 진행하며 거의 쉬지 않고 한 번에 코딩하여 중간 커밋 없이 한 번에 구현되어서 PR 작성할 때는 코드별로 나누어 커밋 진행하였습니다.
네비게이터의 안내를 들으면서도 코드가 한 번에 이해되지 않아 오늘 오랜 시간 코드를 곱씹어보면서 mvc 패턴에 대해 이해하려 노력하였습니다.
### 2. 궁금한 것들
아직 단위 테스트, e2e 테스트의 개념들이 익숙치 않아 어떤 식으로 테스트 코드를 작성해야할 지 잘 모르겠습니다.
컨트롤러의 메서드가 너무 많은 일을 하는 것 같습니다. 뭔가 나누어야할 것 같은데 어떻게 나누어야할 지 잘 모르겠습니다.

2024-04-09 13:53 UTC, hangillee requested changes
안녕하세요, 윤하! 👋

요새 정말 바쁠텐데 페어 프로그래밍 미션 잘 진행해주셨군요! 고생 많으셨습니다.
생소한 개념들이 마구 쏟아지고 있을텐데 잘 정리해서 정말 필요한 것들만 챙겨가는 것을 추천해요!

다음은 남겨주신 질문에 대한 답변입니다.
> 아직 단위 테스트, e2e 테스트의 개념들이 익숙치 않아 어떤 식으로 테스트 코드를 작성해야할 지 잘 모르겠습니다.

괜찮습니다! 원래 테스트를 처음 작성해보면 어려운 것이 당연합니다. 저는 **테스트 코드가 일종의 기능 명세서의 역할**을 할 수 있도록 내가 구현한 기능들의 올바른 사용 방법과 예외 상황에 대한 안내를 모두 작성합니다. 그렇게 하면 테스트 코드만 읽어도 다른 개발자들이 내 코드에 어떤 기능이 있고, 어떻게 하면 정상 동작하고, 어떻게 하면 예외가 발생하는지 파악할 수 있습니다. 즉, 오용하기 어려운 코드를 만들 수 있습니다.

또한 TDD를 경험해보면, 테스트가 프로덕션 코드를 주도하기 때문에 자연스럽게 어떻게 테스트를 작성해야할지 고민할 이유가 사라집니다. 😁

> 컨트롤러의 메서드가 너무 많은 일을 하는 것 같습니다. 뭔가 나누어야할 것 같은데 어떻게 나누어야할 지 잘 모르겠습니다.

적절하게 문제를 파악했네요! 관련해서 코멘트를 남겼으니 확인 후 리팩토링 부탁드립니다!

2024-04-09 13:53 UTC, hangillee commented on docs/README.md
> +    - [x]  랜덤 값이 4 이상일 경우 전진
기능 구현 목록 작성 👍

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +    private val cars: MutableList<Car> = mutableListOf()
Controller가 `Car` 목록을 상태로 가질 필요가 있을까요? 🤔
**일급 컬렉션**에 대해 학습해봅시다!

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +    }
일급 컬렉션을 활용하면 해당 로직도 Controller가 가질 필요가 없을 것 같습니다!

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +}
POSIX New Line에 대해 학습해봅시다!

모든 코드 파일의 끝에는 공백 라인이 있어야 합니다.

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
만약, `distance`값을 직접 변경하는 것이 아니라, 새로운 `distance` 값을 가지는 새 `Car` 객체를 반환한다면..?
불변 객체에 대해 학습해봅시다!

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/view/InputView.kt
> +
불필요한 공백이 한 줄 있는 것 같습니다!

어떤 회사나 팀의 코드에서는 공백도 하나의 컨벤션이 될 수 있습니다.

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/view/OutputView.kt
> +    fun printRaceResult(cars: List<Car>) {
View 계층의 `OutputView`에서 Model 계층의 `Car` 객체를 의존하게 되었네요.

MVC 패턴을 사용한 이유가 많이 없어져 버린 것 같습니다! 고쳐봅시다!

2024-04-09 13:53 UTC, hangillee commented on src/main/kotlin/racingcar/Application.kt
> +        OutputView(),
굳이 외부에서 `InputView`와 `OutputView`를 주입해줄 필요는 없을 것 같습니다.
윤하는 어떻게 생각하나요?

2024-04-09 13:53 UTC, hangillee commented on src/test/kotlin/racingcar/ApplicationTest.kt
> +        assertThat(car.distance).isEqualTo(1)
한 테스트 메소드에는 하나의 `assert`문만 있어야 합니다.

즉, 최소 단위에 대한 테스트만 있어야 하며, 위의 메소드의 경우에는 첫 상태에 대한 테스트(`car.distance`가 처음에는 0이다.)와
이동 후의 상태에 대한 테스트 (`car.distance`가 이동 후에는 1 증가한다.)로 나눌 수 있을 것 같습니다.

2024-04-09 13:53 UTC, hangillee commented on src/test/kotlin/racingcar/ApplicationTest.kt
> +    fun `전진 테스트`() {
테스트 메소드의 이름은 한글로 작성하지 않는 것을 권장합니다.
희박한 확률이지만 한글을 지원하지 않는 IDE에서 해당 프로젝트를 열었을 때, 정상 작동하지 않을 가능성이 있습니다.

한글로 무슨 테스트인지 알리는 것 대신, `@DisplayName` 어노테이션을 활용해봅시다!

2024-04-09 13:53 UTC, hangillee commented on src/test/kotlin/racingcar/ApplicationTest.kt
> +    }
여러 상황에 대한 테스트 👍

2024-04-09 13:53 UTC, hangillee commented on src/test/kotlin/racingcar/ApplicationTest.kt
>      @Test
각 테스트 메소드 사이에 적절한 개행을 넣어주세요! 가독성 측면에서도 개행이 있는 편이 훨씬 낫습니다.

2024-04-09 13:53 UTC, hangillee commented on src/test/kotlin/racingcar/ApplicationTest.kt
테스트 코드는 그 자체로 기능 명세서 역할을 하기도 합니다.
적절하게 테스트 메소드들을 그들이 검증하려는 기능을 가진 클래스의 테스트 클래스로 묶어봅시다!

2024-04-09 14:04 UTC, labyrinth30 commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
상태가 변하지 않음을 보장하는 불변의 힘은 지난 미션을 통해 알게 되었습니다.
여기서는 `moveForward` 함수가 늘어난 `distance` 값을 가진 새로운 `Car` 객체를 반환하도록 구현한다면, 늘어난 `Car` 객체가 잡아먹을 메모리가 걱정되어 그렇게 구현하지 않았습니다.
가비지 컬렉터의 Mark&Sweep 동안 프로그램이 느려질 수 있다. 라고 페어님이 말씀해주셔서 이렇게 구현한 것도 있습니다.
불변 객체를 더 공부해보겠습니다!

2024-04-09 14:05 UTC, labyrinth30 commented on src/main/kotlin/racingcar/view/InputView.kt
> +
공백을 신경쓴다고 했는데도 자잘자잘하게 틈이 있네요. 커밋할 때 줄 단위로 한 번 더 확인해보겠습니다. 감사합니다!

2024-04-09 14:07 UTC, labyrinth30 commented on src/test/kotlin/racingcar/ApplicationTest.kt
클래스로 나눠서 테스트 코드를 분리했더니 전체 테스트 커버리지 보기가 힘들어 마지막에 합쳐봤습니다. 다음 PR 작성 시에는 나눠서 작성해보겠습니다!

2024-05-10 02:11 UTC, hangillee commented
미션 고생 많으셨습니다! 이만 머지하겠습니다.

2024-05-10 02:11 UTC, merged