[자동차 경주] 이인협 미션 제출합니다.
gdsc-skhu-pair-mission/kotlin-racingcar-6 pull request #2
Opened 2024-04-09 07:43 UTC by cucumber99

## 궁금한 점
- MVC 패턴 기반으로 구현하였는데 한 모델에서 다른 모델로, 또는 모델에서 뷰로 데이터를 전달하기 위해서 getter와 DTO를 사용하였습니다. 이 두 가지를 사용하지 않고 구현하려면 어떤 식으로 설계해야 할지 아직 감이 잘 잡히지 않은 것 같습니다. getter를 사용하지 않고 객체가 일을 하게 해야 한다는 것을 이번 미션에서 확실하게 알아가고 싶어요.
- 컨트롤러에서 메소드를 분리하고, 올바른 동작을 위해 `lateinit var` 키워드를 사용하여 모델 객체를 초기화 하였는데 이 방법은 객체의 불변성을 유지할 수 없어서 좋은 방법이 아니라고 생각하고 있습니다. `by lazy` 키워드를 사용하면 불변성은 유지할 수 있을 것 같은데 결국 이 방법들은 객체 간의 결합도를 증가시키는 좋지 않은 방법인 것 같습니다. 리뷰어님의 의견이 궁금합니다.
- Car 클래스에서 자동차의 이름, 위치를 상태로 갖게끔 하였고, Racing 클래스에서는 Car 객체 리스트를 상태로 갖게 하여 구현하였는데 각 자동차의 전진 여부를 결정하기 위한 난수 생성은 Racing 클래스에서 책임지고 있습니다. 이런 경우 자동차의 위치를 Racing 클래스에서 책임져야 할지, 혹은 난수 생성을 Car 클래스에서 책임지게 해야 할지 헷갈렸습니다.
- 테스트 코드를 작성할 때 생각보다 제가 테스트할 수 있는 부분이 많지 않았던 것 같습니다. 제가 아직 테스트 코드를 작성하는데 있어서 미숙한 탓도 있지만, 현재 프로그램의 설계가 다양한 테스트 코드를 작성하기에 적합하지 않은 코드인지 궁금합니다.

2024-04-11 16:58 UTC, vact19 requested changes
> MVC 패턴 기반으로 구현하였는데 한 모델에서 다른 모델로, 또는 모델에서 뷰로 데이터를 전달하기 위해서 getter와 DTO를 사용하였습니다. 이 두 가지를 사용하지 않고 구현하려면 어떤 식으로 설계해야 할지 아직 감이 잘 잡히지 않은 것 같습니다. getter를 사용하지 않고 객체가 일을 하게 해야 한다는 것을 이번 미션에서 확실하게 알아가고 싶어요.

질문의 의도를 잘 모르겠습니다! 지금 말씀하시는 내용이 kotlin 혹은 그와 비슷한 언어에서만 다뤄지는 내용이라면 제가 모르는 내용이므로 좀 더 자세한 설명이 필요할 것 같습니다.
1. 여기서 DTO는 핵심 클래스인 `Car`와, `Car가 활용되는, 프로그램 내에서의 하나의 케이스(현재 게임 상태 반환)`을 분리해주는 역할을 해 주네요. DTO를 충분히 활용할 만 하다고 생각합니다(물론 지금은 Car와 RacingDto가 가지고 있는 값이 같지만요).
2. getter 또한 Car에서 값을 추출해서 DTO로 변환하기 위해 필요해 보입니다.

저는 위 2가지 이유로 `DTO와 getter를 제거`할 필요는 없는 것 같다는 생각이 들었는데,
혹시 제가 모르는 다른 점을 말씀하시는 거라면 말해주세요!

> 컨트롤러에서 메소드를 분리하고, 올바른 동작을 위해 lateinit var 키워드를 사용하여 Racing 모델 객체를 초기화 하였는데 이 방법은 객체의 불변성을 유지할 수 없어서 좋은 방법이 아니라고 생각하고 있습니다. by lazy 키워드를 사용하면 불변성은 유지할 수 있을 것 같은데 결국 이 방법들은 객체 간의 결합도를 증가시키는 좋지 않은 방법인 것 같습니다. 리뷰어님의 의견이 궁금합니다.

by lazy를 사용한다면, prepareRacing()의 로직 모두가 by lazy{}절로 이동하게 되는 게 맞죠? (저는 코틀린을 주로 사용하지 않아 확인차 질문드려요)
그렇다면 제 눈에는 lateinit을 쓰는 게 더 깔끔하고 이해가 잘 가긴 해요.

그러나 이런 불편함을 느낄 때는, 
`구조가 바뀌어야 하지 않을까?` 하는 생각도 해 보시는 걸 추천해요.

저는 백엔드 서버를 만들면서 컨트롤러->서비스의 구조가 익숙해서
중간에 '서비스'계층을 하나 더 두고, 서비스 계층에서는 Racing 객체를 메서드 파라미터로 받은 다음, 지역변수로 사용하면서 로직을 진행해도 괜찮지 않을까? 하는 생각도 들었네요.

아무튼, 눈앞에 보이는 옵션들이 모두 마음에 들지 않을 땐, 시간이 허락된다면
구조를 갈아엎어서 옵션을 늘리는 방식도 고려해보세요!

> Car 클래스에서 자동차의 이름, 위치를 상태로 갖게끔 하였고, Racing 클래스에서는 Car 객체 리스트를 상태로 갖게 하여 구현하였는데 각 자동차의 전진 여부를 결정하기 위한 난수 생성은 Racing 클래스에서 책임지고 있습니다. 이런 경우 자동차의 위치를 Racing 클래스에서 책임져야 할지, 혹은 난수 생성을 Car 클래스에서 책임지게 해야 할지 헷갈렸습니다.

저는 지금 상태가 좋아 보여요. 역시 고민을 거쳐서 나온 결과라 그런지
제가 보기에도 이해가 쉽게 간 것 같네요.
저는 이런 경우
```
1. 시스템의 핵심이 되는 객체 (Car)
2. 1번 객체가 혼자서 수행하기 어려운 것들을 돕고, 협력하는 객체(Racing)
3. 1번과 2번을 호출하면서, 외부 시스템 연동 등 부가적인 작업을 담당하는 객체(여기서는 Controller가 그 역할을 하고 있네요. 저는 백엔드 코드를 작성할 때 아까 말한 'Service'가 이 역할을 하게 하는데, 이것이 클라이언트 애플리케이션을 다룰 때도 유용한 설계인지는 잘 모르겠습니다)
```
이렇게 3가지 역할을 하는 객체들이 있다고 생각하고 일을 분배합니다.
난수 생성을 Car가 한다면, `핵심 객체`인 'Car'가 
'랜덤값을 생성하고 MIN_FORWARD_VALUE랑 비교작업을 하는'일을 맡아야 하는데,
이런 `게임 진행`과 관련된 작업은 `협력 객체`인 'Racing'이 하는 게 좋겠구나!
이런 식으로 생각하는 편입니다.

> 테스트 코드를 작성할 때 생각보다 제가 테스트할 수 있는 부분이 많지 않았던 것 같습니다. 제가 아직 테스트 코드를 작성하는데 있어서 미숙한 탓도 있지만, 현재 프로그램의 설계가 다양한 테스트 코드를 작성하기에 적합하지 않은 코드인지 궁금합니다.

현재 프로그램의 설계가 테스트에 적합하지 않은지는 잘 모르겠습니다.
깃 커밋 로그상 Validator, Output을 테스트하신 것으로 보이는데,
사실 OutputTest는 '언어 차원에서 이미 검증된 println 메서드'를 테스트하게 되기도 하고
프로그램의 핵심이 되는 Car-Racing에 대한 테스트를 페어 분이 맡아 주셔서 그렇게 느끼신 게 아닐까 싶습니다!

> Racing 클래스에서 최종 우승자를 계산하고 우승자 데이터를 View에 전달하기 위해 위와 같은 메소드를 사용하였습니다. MVC 패턴에서 Model이 출력할 메시지를 직접 작성하면 안된다고 알고 있는데, 위 메소드처럼 단순히 우승자를 문자열 리스트로 반환하는 방식은 괜찮은가요?
```
fun getWinners(): List<String> {
    val maxPosition = cars.maxOf { it.position }
    return cars.filter { it.position == maxPosition }.map { it.name }
}
```

네. 제가 보기엔 괜찮아 보입니다,
출력을 위한 '단서만을' 반환하는 것이기도 하고,
'우승 자동차의 이름만을 반환한다'라는 기능은 model이 가지고 있어도 이상할 것이 없는 기능이라고 생각합니다.

2024-04-11 16:58 UTC, vact19 commented on src/main/kotlin/racingcar/model/Car.kt
> +    fun moveForward(shouldMove: Boolean) {
[이것](https://github.com/gdsc-skhu-pair-mission/java-racingcar-6/pull/5#discussion_r1560765423)
을 읽어 보시겠어요? 
저는 결정을 Car에서 내리거나 Racing에서 내리는 것이 자연스럽게 느껴지는데, 
Racing의 결과값을 bool 파라미터로 받아서 전진 여부를 분기시키는 것이
Car의 책임과 Racing의 책임이 섞인 것 같다는 느낌을 받았네요!

인협님의 의도는 동균님의 답변과 비슷하신가요? 
명확한 답은 없는 문제이므로 인협님의 생각이 궁금합니다!

2024-04-11 16:58 UTC, vact19 commented on src/main/kotlin/racingcar/util/Validator.kt
> +object Validator {
무엇에 대한 검증인지를 명시해서 검증 사항을 주제별로 분류할 수 있게 해도 좋을 것 같아요.
InputValidator, GameRuleValidator 뭐 이렇게요!

물론 지금 상황에선 검증사항이 많지 않기에,
객체 분리의 효과는 적은 상황은 맞습니다!

2024-04-11 16:58 UTC, vact19 commented on src/test/kotlin/racingcar/CarTest.kt
> +    fun `전진하는 경우`() {
메서드 내부 구현아 아닌, 시그니처만 보고도 하는 일이 무엇인지 알아야 한다는 말은
테스트 메서드에도 적용됩니다. '어떤 상황에서 어떤 행동이' 일어나길 기대하는지를 적어주세요.
인협님이 ValidatorTest에서 작성하신 `시도 횟수가 1 미만이면 예외가 발생한다()` 가 좋은 예가 되겠네요!

RacingTest 또한 좀 더 섬세하고 명확하게 바꿔주시면 좋을 것 같아요.

2024-04-12 08:52 UTC, cucumber99 commented on src/test/kotlin/racingcar/CarTest.kt
> +    fun `전진하는 경우`() {
테스트 코드를 제대로 짜고 있지 못했던 것 같습니다. 감사합니다.

2024-04-12 08:57 UTC, cucumber99 commented on src/main/kotlin/racingcar/model/Car.kt
> +    fun moveForward(shouldMove: Boolean) {
모델을 Car와 Racing으로 나누어서 코드를 작성할 때, Car는 순전히 자동차의 기능을 갖고 있게끔 하기 위해서 `moveForward` 메소드 하나만을 작성하였고, Racing에서는 생성된 Car 객체를 이용하여 게임을 진행시키는 기능을 갖게 하기 위해 난수를 생성하고 결과에 따라 자동차가 움직일 수 있도록 코드를 작성하였습니다.

2024-04-12 09:53 UTC, cucumber99 commented
좋은 리뷰 감사합니다. 많은 생각을 하게 되는 시간인 것 같습니다.

제가 getter를 쓰지 않고 구현하고 싶다고 말씀드렸던 것은 다른 언어에서도 마찬가지겠지만, getter를 지양하라는 말을 정말 많이 들었습니다.  무분별한 getter가 아니라면 괜찮다고 하지만, 저는 최대한 getter를 사용하지 않고 Racing 객체가 직접 행동하게끔 구현을 하고자 했습니다. 
그러나 Controller에서 게임을 진행하며 Racing 객체의 상태가 바뀌었을 때 View를 통해 데이터를 화면에 출력하는 등의 동작을 위해서는 Controller 내부에서 Racing 객체를 직접 인스턴스화하여 사용할 수 밖에 없었습니다. 이러한 방식은 getter를 사용할 뿐만 아니라 객체의 불변성을 유지할 수 없는 등 여러 문제가 있다고 생각했습니다. 페어 프로그래밍을 시작하고 항상 이 부분에 대해서 많은 고민을 하고 있었는데, 아무래도 제가 언어에 대한 이해도도 아직은 낮고 필력도 모자라서 리뷰어님이 정확하게 이해할 수 없었던 것 같습니다.

말씀하신 것처럼 Racing 객체를 메소드의 인자로 전달하고, 지역변수로 사용하는 방법이 좋은 해결책이 될 수 있을 것 같다는 생각이 듭니다. 좋은 리뷰 감사합니다.

2024-04-18 09:55 UTC, vact19 approved these changes
> 제가 getter를 쓰지 않고 구현하고 싶다고 말씀드렸던 것은 다른 언어에서도 마찬가지겠지만, getter를 지양하라는 말을 정말 많이 들었습니다. 무분별한 getter가 아니라면 괜찮다고 하지만, 저는 최대한 getter를 사용하지 않고 Racing 객체가 직접 행동하게끔 구현을 하고자 했습니다...(후략)

무분별한 Getter보다는 객체가 직접 행동하도록 설계해야 한다는 조언의 의도는 아마

1. 너무 많은 필드에 대해 getter를 열어놓아서 혼잡성을 늘릴 수 있다.
2. 객체 내부의 메서드가 일을 하는 게 아니고, 객체를 호출하는 곳에서(예를 들어, Racing 클래스) getter를 사용해서 값을 빼온 후 로직을 작성하게 된다. 이는 Car 객체를 `내부에 로직이 위치하는` 능동적인 객체로 만드는 것이 아닌, 단순히 `값을 담고 꺼내는 수동적인 역할`을 하게 한다('object를 struct처럼 쓰면 안 된다'라는 말도 있더라구요).

이런 의도를 가지고 나온 조언인 것 같아요.
그러나 지금의 경우는 1, 2번의 주의사항에 크게 해당되지 않는 것 같아요!

그중의 한 예로,
getter를 사용하지 않고 RacingDto를 생성하려면
Car 클래스가 RacingDto를 반환해야 하는데, 
이러면 Car에 `단순 데이터 전송용 클래스인 RacingDto에 대한 의존성`이 
추가되는 문제도 있고 그렇죠.

---

리뷰가 늦어 죄송하구, 고생하셨습니다!
머지해도 될 것으로 판단되어 머지를 진행하겠습니다만은!
남겨놓은 글(Car 생성자 문제)을 읽어보시면서 이 문제도 한번 생각해보면
굉장희 유익할 거 같아요~

2024-04-18 09:55 UTC, vact19 commented on src/main/kotlin/racingcar/controller/Controller.kt
> +        showWinners(racing)
처음 제출하셨을 때는 코드가 이렇게 되어있었는데
```java
prepareRacing()
processRacing()
showWinners()
```
예전에는 각각의 메서드들이 controller 내부의 Racing 객체 상태를 어떻게 변경 하는지를
로직 하나하나를 살펴보며 일일히 추적해야 했는데
이렇게 값을 반환하고, 파라미터로 전달하는 것이 외부에서 보이니까 흐름 이해가 훨씬 편하네요!

2024-04-18 09:55 UTC, vact19 commented on src/main/kotlin/racingcar/controller/Controller.kt
> +        val racing = Racing(cars.map { Car(it) })
다른 분의 작업을 리뷰하면서 `Car의 name 검증에 대한 책임은 누가 지도록 해야 하는가?`
에 대한 나눴었는데, 이 부분 읽어보시면서 한번 생각해보셔도 좋을 것 같습니다!

- https://github.com/gdsc-skhu-pair-mission/java-racingcar-6/pull/5#pullrequestreview-1993765544
- https://github.com/gdsc-skhu-pair-mission/java-racingcar-6/pull/5#issuecomment-2053889473
- https://github.com/gdsc-skhu-pair-mission/java-racingcar-6/pull/5#pullrequestreview-2004058826

2024-04-18 09:55 UTC, vact19 commented on src/test/kotlin/racingcar/CarTest.kt
> +    @DisplayName("난수가 4 이상인 경우 자동차는 전진한다.")
적절한 테스트 이름이네요! '규칙' 그리고 '발생하는 결과'를 모두 포함하고 있습니다.

2024-04-18 09:57 UTC, merged

2024-04-19 03:09 UTC, cucumber99 commented
좋은 리뷰 감사합니다! 고생하셨습니다.