[자동차 경주] 남궁혜민 미션 제출합니다.
gdsc-skhu-pair-mission/kotlin-racingcar-6 pull request #3
Opened 2024-04-09 09:21 UTC by hyeminililo

설계 : 코틀린 이용해, MVC패턴을 이용해서 Car와 Racing Car 클래스를 이용해 랜덤 자동차 게임을 만들었습니다. 
궁금한 점  : 처음에 모델을 작성할 때, Model의 역할을 어떻게 나눠야할지 잘 모르겠어서, 고민을 많이 했습니다. 그래서 페어의 도움으로 dto와 컨트롤러를 이용해서 구현했습니다. 그래서 앞으로 MVC 패턴을 잘 이용하는 법이 궁금합니다. 또한 테스트 코드 작성할 때, 테스트 코드를 메소드 별로 나눠서 테스트 코드를 작성했습니다. 그런데 , 랜덤변수를 만드는 메소드와 같이 라이브러리를 이용해 만든 메소드도, 테스트 코드를 만들어야 하는지 궁금합니다.

2024-04-11 08:09 UTC, HanHyunsoo requested changes
안녕하세요 혜민님 리뷰어 한현수입니다.

만든 프로젝트 잘봤고 아쉬운점 몇가지 아래에 적어드릴게요.

1. MVC 패턴으로 잘 개발하셨지만 특정 클래스가 해당 역할을 하는지 의문이 들어요. 좀 더 고민하시고 메서드의 역할을 다른 영역으로 변경하여 패턴을 지켜보세요!
2. 메서드 내부 변수를 봤을 때 어떤 타입인지 잘 모르겠어요. type hint를 적으시는 건 어떠신가요?
3. 테스트 코드도 아쉬운점이 많아요. 한 메서드에 대해 실패하는 케이스와 성공하는 케이스 모두 적으시고 정상적으로 작동하는지 확인하시면 좋을 것 같아요.

### 궁금한 점에 대한 답변

* MVC 패턴을 잘 이용하는 법이 궁금합니다. 
  * 'MVC 패턴을 잘 구현하는 방법' 보다는 'MVC 패턴이 필요한 이유와 장단점'에 대해 공부하시면 자연스럽게 잘 이용하는 방법에 대해 아시게 될 거에요. MVC패턴으로 분리한 클래스들을 한 클래스에 몰아서 하면 불편한점이 많겠죠?
* 랜덤변수를 만드는 메소드와 같이 라이브러리를 이용해 만든 메소드도, 테스트 코드를 만들어야 하는지 궁금합니다.
  * 릴리즈된 라이브러리도 대부분 테스트코드를 통해 검증됬기 때문에 혜민님이 라이브러리를 이용해 만든 로직에 대해서만 테스트 코드를 작성하면 될 것 같습니다.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/model/Racing.kt
> +    private val cars: List<Car>
List는 immutable 속성을 가지는데 계속 car가 추가된다면 MutableList가 더 적합할 것 같아요.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/model/Racing.kt
> +        val maxPosition = cars.maxOf { it.position }
변수에 대해 Type Hint를 적는 것이 더 가독성 있을 것 같습니다.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/util/Error.kt
> +enum class Error(private val message: String) {
enum으로 예외를 관리하는 것도 좋지만 IllegalArgumentException를 상속한 예외 클래스를 여러개 만들어서 처리하는 것이 좀 더 객체 지향적일 것 같습니다.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/model/Car.kt
> +    fun moveForward(shouldMove: Boolean) {
매개변수를 통해서 위치 증가 여부를 고려하는 로직을 controller에 위임하는 것이 좋을 것 같아요.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/controller/Controller.kt
> +    private lateinit var racing: Racing
Racing이 교체되는 상황은 없으니 var대신 val로 변경하시는게 좋을 것 같아요.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/view/Input.kt
> +    fun getCars(): List<String> {
해당 메서드를 봤을 때 Car 리스트를 반환하는 것인 줄 알았는데 String 리스트를 반환하는 것이여서 메서드명을 변경하시면 좋을 것 같습니다.

2024-04-11 08:09 UTC, HanHyunsoo commented on src/main/kotlin/racingcar/model/Racing.kt
> +        val maxPosition = cars.maxOf { it.position }
그리고 해당 메서드가 모델의 역할인지 의문이 들어요. Controller에 처리하는 것이 MVC 패턴에 더 어울릴 것 같아요.

2024-04-15 08:25 UTC, hyeminililo commented on src/main/kotlin/racingcar/model/Racing.kt
> +        val maxPosition = cars.maxOf { it.position }
반영했습니다 :) getWInner를 Controller 클래스로 옮기는 과정이 리팩토링 과정에서 가장 어려웠던 것 같습니다.

2024-05-20 11:41 UTC, HanHyunsoo approved these changes

2024-05-20 11:41 UTC, merged